### ISSUE TITLE
BL list of assigned manuscript ids

### ISSUE THREAD

**Issue by julian-cook-bl-uk** [fihristorg/fihrist-mss#124]
Could someone (Andrew M.?) please remove all manuscript ids up to and including manuscript_32712 from the **british_library.txt** file in /identifiers folder? I would do it myself but the file says DO NOT EDIT. Reason: we are about to begin a new batch of records and want to avoid duplicate ids.

**Comment by andrew-morrison** [comment]
The reason those files say not to edit them is because there is always a chance that two people from one institution may be working on their records at the same time. In which case, if one person removed manuscript IDs from the file as they used them, but didn't push that change from their local copy to GitHub, or the other person didn't pull from GitHub to their local copy before starting work on a new manuscript, they could end up using the same IDs.

It is up to each institution to keep track of usage of the IDs that have been allocated to them. One way would be to update the last used ID on [this wiki page](https://github.com/fihristorg/fihrist-mss/wiki/Last-Used-Manuscript-IDs). Or you could copy and paste all your IDs into a spreadsheet on an internal system, such as SharePoint. Then you could tick them off as you use them, or divide them up between cataloguers or collections.

The only point at which I should get involved is when you've run out of manuscript IDs and need a new list to be generated.

**Comment by julian-cook-bl-uk** [comment]
Thanks Andrew - I have gone ahead and deleted those ids we have used. 

Just in case anyone else is wondering how to find the highest manuscript id they have used here is a simple XQuery: declare namespace tei="http://www.tei-c.org/ns/1.0"; max(//tei:TEI/@xml:id[substring-after(.,'manuscript_')]/xs:int(substring-after(.,'manuscript_'))) . I use a product called BaseX (free) to point at a folder, create a 'database' of those TEI files and run this XQuery.  But one can run the same in Oxygen XPath/XQuery Builder (with any of the Saxon XQuery options).

**Comment by julian-cook-bl-uk** [comment]
Am unable to edit the Wiki page you mentioned - suspect do have edit rights.

**Comment by andrew-morrison** [comment]
You were a member under a different account. I've sent an invitation to your BL email address. Accept that while logged in with your BL account, and you should then be able to edit the wiki.

No method of finding the highest manuscript ID can find IDs used by someone else in a new record not committed and pushed yet. That is why some other means of keeping keeping track of IDs is needed.

**Comment by andrew-morrison** [comment]
For example, you say you have used IDs up to `manuscript_32712`, but that ID isn't in any of the records on the master branch yet. And, now that you've edited it, it isn't in `identifiers/british_library.txt` either. So, if I generated a new list for someone else, they'd be allocated that ID.

**Comment by julian-cook-bl-uk** [comment]
Aha - now I see the problem - hadn't realized how you automate this - I will put the used ones back in pronto!

Thanks for adding BL me to the FIHRIST repo - went ahead and edited the Wiki page with a simple XQuery to find highest number used (below the table).

Thanks Andrew.

All the best

Julian
