### ISSUE TITLE
Person with two LC & VIAF entries!q

### ISSUE THREAD

**Issue by kontovasBodleian** [fihristorg/fihrist-mss#145]
The person محمد بن علي سباهي زاده is currently in Fihrist with his id "person_21607038", corresponding to <a href="https://id.loc.gov/authorities/names/n2007227637.html">this VIAF entry</a>; however, he also has <a href="https://viaf.org/viaf/18164115083910052666/#Sipa%CC%82hi%CC%82za%CC%82de_Mehmed,_-1589">a separate VIAF entry</a> under the Turkish spelling of his name! This seems to be replicating a mistake made by LC, which similarly has two entries, one for "<a href="https://id.loc.gov/authorities/names/n2007227637.html">Sibāhī Zādah, Muḥammad ibn ʻAlī, -1589</a>" and another for "<a href="https://id.loc.gov/authorities/names/no2021151092.html">Sipâhîzâde Mehmed, -1589</a>"

Obviously, this problem is ultimately bigger than Fihrist, and I've already reported it tot the BMAC team here at Oxford, who are authorised to propose changes to LC authority entries. But this does raise the question: What should I do with the authority entry? Should I add a link to the alternative VIAF & LC pages? How should I do this?

Just assigning two people I thought would have lots of experience with this stuff, so forgive me for bothering ppl who may not know/care!

**Comment by yf227** [comment]
Hi Niko

We should have him under one entry in Fihrist. If it then gets deleted in VIAF without being re-directed, that’s bad but can’t be avoided.
I don’t think a person can have two VIAF IDs on Fihrist. I am also not sure about a comment including that type of info under the persons heading in the authority file.
Let me know which heading you prefer and we can meet on Zoom and I will show you how to do it.

Best
Yasmin

From: Nicholas Kontovas (professional account) ***@***.***>
Sent: 18 July 2023 16:47
To: fihristorg/fihrist-mss ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fihristorg/fihrist-mss] Person with two LC & VIAF entries!q (Issue #145)


The person محمد بن علي سباهي زاده is currently in Fihrist with his id "person_21607038", corresponding to this VIAF entry<https://id.loc.gov/authorities/names/n2007227637.html>; however, he also has a separate VIAF entry<https://viaf.org/viaf/18164115083910052666/#Sipa%CC%82hi%CC%82za%CC%82de_Mehmed,_-1589> under the Turkish spelling of his name! This seems to be replicating a mistake made by LC, which similarly has two entries, one for "Sibāhī Zādah, Muḥammad ibn ʻAlī, -1589<https://id.loc.gov/authorities/names/n2007227637.html>" and another for "Sipâhîzâde Mehmed, -1589<https://id.loc.gov/authorities/names/no2021151092.html>"

Obviously, this problem is ultimately bigger than Fihrist, and I've already reported it tot the BMAC team here at Oxford, who are authorised to propose changes to LC authority entries. But this does raise the question: What should I do with the authority entry? Should I add a link to the alternative VIAF & LC pages? How should I do this?

Just assigning two people I thought would have lots of experience with this stuff, so forgive me for bothering ppl who may not know/care!

**Comment by andrew-morrison** [comment]
The Fihrist authority entry for this person can link to multiple VIAF entries (and multiple LC ones.)  Just create another `<item>` in the `<list type="links">`, containing a `<ref>` with a `target` attribute pointing to the new VIAF URL. At some point, VIAF may deduplicate its two records, and it may choose to keep the other ID, and delete the ID that the  Fihrist entry is based on. But that doesn't matter. All that is necessary is that ID remain stable and unique. VIAF doesn't re-use old IDs, so there is no need to change a Fihrist person ID just because the VIAF ID it was originally based on has been retired.

**Comment by yf227** [comment]
Excellent!
Thanks Andrew!
Niko, you may wish to add this to the documentation on the GitWiki?
All the best
Yasmin


Yasmin Faghihi
Head of Near and Middle Eastern Department
Manuscripts and Printed Collections
Cambridge University Library
West Road
CB3 9DR UK
Tel.: +44 1223 764739
Email: ***@***.******@***.***>
FIHRIST | https://www.fihrist.org.uk/
Cambridge Digital Humanities | https://www.cdh.cam.ac.uk/about/people/yasmin-faghihi/
Twitter | @YasminYf227<https://twitter.com/CamDigLib?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>

https://www.cdh.cam.ac.uk/media/blog/investigating-the-origins-of-islamicate-manuscripts-using-computational-methods/

**Comment by kontovasBodleian** [comment]
Ah, great. I'll take care of that at the end of this week and make a note on the Wiki.

Thanks everyone for your input!
