### ISSUE TITLE
Shah Rukh works

### ISSUE THREAD

**Issue by JakeBenson** [fihristorg/fihrist-mss#146]
I just noticed that under the [person ID for Shah Rukh](https://www.fihrist.org.uk/catalog/person_24010955), [one title](https://www.fihrist.org.uk/catalog/work_23094) only appears in the vernacular script. Not sure how that happened, as the transliterated title _Min el-nevādir_ appears in the associated record? Any way to fix the display?

**Comment by andrew-morrison** [comment]
Whoever is currently editing the works authority could change this by setting by changing the _type_ attributes in the _title_ elements in the entry for work_23094 in works_base.xml. The _title_ with the _type_ of "uniform" is the one that will be displayed on the web site, on its own page and in links to it from person pages.

**Comment by kontovasBodleian** [comment]
This is my fault! I have a tendency to put my original script titles/names first, but I only recently noticed that this makes the script choose it as the `@type=uniform` option. I have gone through and fixed the one you caught, @JakeBenson, as well as a couple others I noticed. Thanks!

@andrew-morrison : Is there a way to force a different title to be chosen as  `@type=uniform` for the authority entry, regardless of its order within the `<msItem>`?

**Comment by andrew-morrison** [comment]
The de facto Fihrist style seems to be to put the transliterated title (or persName for authors) first. It would probably be best to stick with that, and maybe formalize it in documentation, rather than complicate things by adding an attribute to indicate which form the cataloguer thinks should be preferred. It is part of the editorial role make that decision, by changing which has is `type="uniform"` (or `type="display" for people.)

**Comment by kontovasBodleian** [comment]
Gotcha. My only issue with that is that it becomes a bit awkward when embedded in prose to add the possessive ending when you put the original script second (i.e. "بابر Bābur's works" looks better than "Bābur بابر's works") but I'm sure I'll learn to cope ;-)
