### ISSUE TITLE
Issues with works - missing hyperlinks to work and disambiguation of work codes (titles)

### ISSUE THREAD

**Issue by cookjools** [fihristorg/fihrist-mss#61]
I want to assign a key attribute value (work_...)  to the <title> elt for a manuscript of Rasāʾil Ikhwān al-Ṣafā and ran into a couple of issues. 

I find there are other copies already in Fihrist for example:
https://www.fihrist.org.uk/catalog/manuscript_8585 [ms. 45812 (SOAS)] However,...

**Problem 1:  lack of a hyperlink from a work in a manuscript to the associated work record:**
When I view the SOAS record https://www.fihrist.org.uk/catalog/manuscript_8585 the titles (unlike the author) do not have a hyperlink:
Author: Ikhwān al-Ṣafāʼ اخوان الصفاء
Title: Rasāʼil
Title: رسائل

This means:
(1)	it is not as simple as it should be to list other copies.
(2)	for my current purposes (recording another copy) it is not a simple matter to recover the work_code 

Workaround (a) one way to find the work code is to examine the SOAS record in the repository (https://github.com/fihristorg/fihrist-mss/blob/master/collections/school%20of%20oriental%20and%20african%20studies/ms_45812.xml ) I can see the work key is work_1066
So it would seem I should simply mark up the new ms copy with that same code using
<title xml:lang="ar-Latn-x-lc" key="work_1066">Rasāʼil</title> or similar.

Workaround (b): Another way to find the work code would be to search under Works for the title – with results as follows: https://www.fihrist.org.uk/?utf8=%E2%9C%93&f%5Btype%5D%5B%5D=work&q=Ras%C4%81%CA%BCil  where the item we want appears first: https://www.fihrist.org.uk/catalog/work_1066 

But now I find...

**Problem 2: there are multiple distinct works by different authors are grouped together under title Rasāʼil  indexed as work_1066 – disambiguation is required for this title and presumably others**

Data editing / data curating work is required to separate this title and others like it into distinct works (distinct ids). It seems the default was to assume that the same title means the same work. 

Suggestion: some of the disambiguation work could be automated it seems to me: if a ‘work’ (title) has manuscript instances associated with distinct authors then those should be assigned to different work id’s. Thus the Rasāʾil of Ṣābī should have a different work code from the Rasāʾil of the Ikhwān al-Ṣafāʾ.

Note: disambiguation is the opposite problem to the deduplication problem which was mentioned a number of times during the workshop in Oxford.

**Comment by andrew-morrison** [comment]
Re: Problem 1 - displaying work titles as links is on the list of features to add, and is already logged here, see issue #53 

Re: Problem 2 - some automated disambiguation of works might be possible, but it would make sense to deduplicate people first. Otherwise, for example, it would create three work records where there are currently one* for [Gulistān](https://www.fihrist.org.uk/catalog/work_145), for each of the following three authors:

https://www.fihrist.org.uk/catalog/person_100206721
https://www.fihrist.org.uk/catalog/person_f3747
https://www.fihrist.org.uk/catalog/person_100206709

All three of which seem to be the same person, two because VIAF has two records, and one local.

 \* There is currently one work record for title of Gulistān but there are also [24 other work records containing that word](https://www.fihrist.org.uk/?utf8=%E2%9C%93&f%5Btype%5D%5B%5D=work&q=Gulist%C4%81n). Some might be the same thing, so need deduplicating. Others are derivative works, including [commentaries by four different authors grouped into one work record](https://www.fihrist.org.uk/catalog/work_78) which could be disambiguated if that is desirable, or merged with others if that is preferred.
