### ISSUE TITLE
Descriptive titles displaying in italics

### ISSUE THREAD

**Issue by eifionjones** [fihristorg/fihrist-mss#62]
Chip Coakley, who is cataloguing Syriac mss for Fihrist, has asked if titles tagged \@type="desc" (i.e. descriptive titles) could be displayed without italics. Do we want to do this for Fihrist? And is this something which would be generally applicable across other catalogues?

**Comment by holfordm** [comment]
This is indeed how we already do it in Medieval!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by IgnatG** [comment]
I'm currently working on a way to normalize how text is rendering on all TEI websites - CSS wise. I'll investigate this as well as I know it's not italic on others.

**Comment by andrew-morrison** [comment]
Titles in Fihrist are currently set to be italic in the XSLT. This will change when they also become links to work records soon. But there are types other than just "desc". Medieval currently displays only titles with no type attribute in italic. In Fihrist, there are many more types, many of which presumably should be italic:
```
  45027 <no type attribute>
   5411 original
   2504 alt
   2191 desc
    990 standard
    166 supplied
    114 main
    100 normalised
     38 sub
     16 other
      1 translated
      1 short
      1 per-Latn-x-lc
      1 heading
```
We'll set them up to all display in italic except "desc" unless we hear otherwise.

**Comment by IgnatG** [comment]
this should be fixed now on QA - all websites should render such text the same way.

**Comment by andrew-morrison** [comment]
Fix now on the production web site.
