### ISSUE TITLE
Question about where 'Comment on this record' points

### ISSUE THREAD

**Issue by awatson67** [fihristorg/fihrist-mss#66]
Hello. I am going to be updating obsolete email addresses in our Oxford Fihrist records, and had a question where the messages from 'comment on this record' form are currently directed.

Many thanks

**Comment by yf227** [comment]
Hi Alasdair

I think they are, Let’s run some testing…
Best
Yasmin

**Comment by andrew-morrison** [comment]
If a "Comment on this record" link appears it means an `email` field has been found in the TEI file (a small percentage of classmarks do not, e.g. the Wellcome Collection ones). If it is in the `publicationStmt` section, inside an `addrLine` within `address` in `pubPlace`, it'll use that. If not, it'll look for one in the `additional` section, inside `adminInfo`, under `availability`.

If that isn't what you've found with your test, please report back. Otherwise, can this issue be closed?
