### ISSUE TITLE
tagging organizations

### ISSUE THREAD

**Issue by awatson67** [fihristorg/fihrist-mss#67]
In a recent record - MS. Pers. d. 102, I tried tagging Sotheby's thus in <history>:

<acquisition when="1952-03-31"><name type="org" key="org_126386983">Sotheby's</name> (Lot 18) 31st March 1952.</acquisition>

This is using the viaf number for the organization. Is this ok?

Thanks!

**Comment by andrew-morrison** [comment]
That is valid TEI. But instead of...

`<name type="org" key="org_126386983">Sotheby's</name>`

...you could use...

`<orgName key="org_126386983">Sotheby's</orgName>`

...which is the standard that has been adopted by the Medieval catalogue.

However, the Medieval catalogue web site has somewhere to include these (organizations are treated as places, being mostly monasteries, churches, etc) but Fihrist currently does not (it has a subjects index instead of a places index.) Someone has previously tagged Sotheby's as a person, like this...

`Bought from <persName key="person_f4085">Sotheby's</persName>`

...which means there is a person record here...

https://www.fihrist.org.uk/catalog/person_f4085

I'm not sure that is correct, but it is an editorial decision.
