### ISSUE TITLE
Editing Wellcome records

### ISSUE THREAD

**Issue by rmaxton** [fihristorg/fihrist-mss#69]
Hi Andrew,

I am currently editing all the Wellcome records on FIHRIST (transliteration, layout, VIAF links etc.) and I was just wondering what the best way for doing this is. 
I basically made a copy of all the Wellcome TEI files and am working on them locally, but when I want to upload in a batch (i.e. 10 or so), do I simply copy and paste into the Github folder, replacing the already existing records? Or is there a more efficient way?

Many thanks,

Rosie

**Comment by andrew-morrison** [comment]
So, are you working on both Trinity and Wellcome records concurrently, and want to keep them separate?

**Comment by rmaxton** [comment]
Yes, correct! And I would like to be able to work on them locally (particularly the Wellcome ones) and experiment with the layout etc. before uploading them in groups.

**Comment by andrew-morrison** [comment]
There is a mechanism to do this in GitHub, called [branching](https://guides.github.com/introduction/flow/), but it would probably seem unintuitive and overly-complicated to anyone but a software developer. So you are probably best continuing doing what you've done.

Just remember, when you copy and paste files back into the original "wellcome trust" folder, then go to GitHub Desktop to commit and push them, first check that the list of changes files is what you expect, and untick any that aren't ready to go on the web site. Then click on each file in the list in turn, and review the differences (it will display lines from the old version in red, and new lines in green). That is in case someone else has modified the same files since you took your copy. If so, you'll have to combine yours and theirs. The longer you keep working on a separate copy, the greater the risk of that happening.

You might need to repeat the steps to configure Oxygen to preview the layout as it will appear on the web site when working on the separate copy of the Wellcome files. In case you need it, [here are the instructions](https://github.com/fihristorg/fihrist-mss/files/2549422/Presentation.2.record.preview.pptx) again.

**Comment by andrew-morrison** [comment]
I noticed you have added a batch of new Wellcome records. There are some problems with them, as follows, in order of importance:

1. The `<msDesc>` must be inside the `<sourceDesc>` in the `<teiHeader>`. The `<body>` is where you'd put a full transcription, if you had one.
2. They are lacking schema declarations at the top. You can copy and paste those [from here](https://github.com/fihristorg/fihrist-mss/wiki/Creating-a-new-TEI-file).
3. Some files now have `<institution>The Wellcome Trust</institution>`, whereas before there was only `<institution>Wellcome Trust</institution>`. That will create two links on the Fihrist home page, and it won't be possible to list all Wellcome manuscripts in one place.
4. The web site is not set up to handle multiple `<collection>` elements. It will simply join them together into one (e.g. "Asian Collection Iskandar").

If these are a work in progress, that's OK. I usually update the web site on Mondays, but it can wait. However, there are other people's changes waiting to be published, so if it is likely to take more than a week, it might be time to reconsider branching. Alternatively, a method to commit and push records but indicate that they are not ready to be published on the web site is to delete (or comment out) the manuscript ID. For example, if you changed this:
```
<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:id="manuscript_15670">
```
to this:
```
<TEI xmlns="http://www.tei-c.org/ns/1.0"><!-- xml:id="manuscript_15670"-->
```
Then that record won't be published until you are ready (at which point, change it back to the first version).

**Comment by rmaxton** [comment]
Hi Andrew,

Many thanks for highlighting these issues. I will try my best to deal with them today!

**Comment by amme2** [comment]
Regarding point 3. I'd actually prefer the `<institution>` name to be 'Wellcome Collection' in line with our current branding. If Rosie changes all of the records to this, will the Fihrist home page automatically adjust to the new name?

**Comment by andrew-morrison** [comment]
If Rosie changes all of the records, commits and pushes, and there are no other issues, the home page will change after I re-index.

**Comment by amme2** [comment]
And on point 4. Is specifying a `<collection>` mandatory? We are trying to eradicate terminology like 'Asian Collection' as these are essentially former departmental/management categories which aren't helpful to the user and can also be problematic. Similarly, Iskandar is merely the original cataloguer, and is acknowledged anyway as an `<altIdentifier>`. 

To summarise, and now contradicting what I said above (sorry, just thinking it through as I write), I think my preference would be:

`<institution>Wellcome Trust</instution>
<repository>Wellcome Collection</repository>`

and no `<collection>` tags. Is this acceptable?

**Comment by andrew-morrison** [comment]
The home page would have a link entitled "Wellcome Trust". That would also be the option in the Institution filter when searching. In the Collection filter, your records would be included with a few others in an option called "Not specified". There is no search filter for repository. And each record would display with a title like this:

>MS Arabic 430 (Wellcome Collection, Wellcome Trust)

If that is what you want, it is not a problem for anything else.

**Comment by andrew-morrison** [comment]
@rmaxton, @amme2: I've re-indexed the Fihrist web site, so your changes to the Wellcome records are now visible.

I'm closing this issue, feel free to re-open it if you have more questions.
