### ISSUE TITLE
Committing changes to records

### ISSUE THREAD

**Issue by rmaxton** [fihristorg/fihrist-mss#78]
Dear Yasmin and Andrew,

I hope you're doing well.
I am basically contacting you as I have been committing changes to Wellcome records and uploading new Trinity records for the past month, and I am a bit concerned that they are not appearing on the website.
I was therefore wondering if there were any problems with my edits, or if the frequency of updating the website has been changed?
Any news you have would be much appreciated, as I would very much like to show these institutions what I've been up to!

Many thanks,
Rosie

**Comment by andrew-morrison** [comment]
The last time the Fihrist web site was updated was January 15th. Since then records have been added which contain the same manuscript IDs as other ones. They all have to be unique, otherwise what is at https://www.fihrist.org.uk/catalog/manuscript_1234 today could be replaced with something else tomorrow. So the indexing script it set up to fail when even a single manuscript ID has been used more than once.

If you are subscribed to the Fihrist mailing list, you should've received an email about this, from Yasmin, on January 17th.

I've checked again today, and there are 29 IDs used twice or more in 64 different TEI files currently committed and pushed to this repository. All belong to either Cambridge University Library or Trinity College Cambridge (there were some SOAS ones, but they've fixed theirs.) The [attached spreadsheet](https://github.com/fihristorg/fihrist-mss/files/2900126/fihrist_duplicate_manuscript_ids_20190225.xlsx) lists them.

**Comment by amme2** [comment]
Hi Andrew

Are you saying that we will have to wait for CUL and Trinity to resolve the number duplication before the Wellcome records can be updated, even though there's no duplication in the records we've (well, Rosie) committed?

Alexandra

**Comment by rmaxton** [comment]
Dear Andrew,

Many thanks for this. I think the issue seems to be that the Trinity
records already on Fihrist when the updating was carried out were assigned
these manuscript IDs which are now duplicate. I was then given the range of
IDs from 12930-13040, however I didn't think to apply this numbering to
records already uploaded on the website, just the new ones I was creating.

Does this mean I need to start the entire collection (including those
already on the website with an MS ID) from 12930?

Sorry for any confusion, I just hadn't fully understood how you wanted us
to proceed with the numbering.

Best wishes,
Rosie

**Comment by yf227** [comment]
Dear all

I must admit, I am a bit behind with all this, but I asked Chip to change all the ID of the Syriac records and committed them again with newly allocated numbers.
Trinity is also done by Rosie, so she can keep control over those.
I will double check asasp but I hope we can solve this easily.
Best
Yasmin

Yasmin Faghihi
Head of Near and Middle Eastern Department
Manuscripts and Printed Collections
Cambridge University Library
West Road
CB3 9DR UK
Tel.: +44 1223 764739
Email: yf227@cam.ac.uk<mailto:yf227@cam.ac.uk>
Chair Middle East Libraries COMmittee (MELCOM) UK
http://www.melcom.org.uk/
Co-Chair FIHRIST
http://www.fihrist.org.uk/home

**Comment by andrew-morrison** [comment]
To answer Alexandra's question: Yes, nothing can be published until there are no duplicate IDs. Because, as well as preventing one person from replacing another's record at an existing URL, re-indexing everything is required to build the links to manuscripts from work, person and subject pages.

**Comment by rmaxton** [comment]
Dear all,

I have just corrected all the Trinity College Cambridge MS ids which were
duplicates.
Hopefully this will sort the issue out - my apologies for the delay in
doing so!

Best wishes,
Rosie

**Comment by andrew-morrison** [comment]
There are now four manuscript IDs which are used in two or more TEI records. Two of them are in Trinity College Cambridge's files. Two are in Cambridge University files. Here is an [updated spreadsheet](https://github.com/fihristorg/fihrist-mss/files/2919609/fihrist_duplicate_manuscript_ids_20190301.xlsx).

**Comment by andrew-morrison** [comment]
Hi Rosie and others,

The Fihrist web site has now been updated for the first time since January 15th.

Andrew.
