### ISSUE TITLE
Next indexing

### ISSUE THREAD

**Issue by yf227** [fihristorg/fihrist-mss#81]
Hi Andrew 
When are you going to run the index next? I am asking because the scholar who has created the Syriac MS descriptions (which I only added today) is keen to proof read his work on FHRIST on 25 June when he is next in the Library. Would this fit with your schedule?
Many thanks. Ysmn

**Comment by andrew-morrison** [comment]
I would re-index now, but there are some duplicate IDs:

* manuscript_11858:
   * cambridge university/Or_1081.2.75.xml
   * cambridge university/Or. 1081.2.75.xml
* manuscript_11850:
   * cambridge university/Or_690.xml
   * cambridge university/Or. 690.xml

However, looking more closely, those are just the ones that fail because they have the same ID. There are lots of other pairs which have different IDs inside the TEI but, judging by their filenames, they are describing the same manuscript. If you delete one each of the two pairs above, I'd be able to re-index, but there would then be duplicates records on the Fihrist web site for all of these:
```
BSMS 443.xml    BSMS_443.xml
BSMS 444.xml    BSMS_444.xml
BSMS 445.xml    BSMS_445.xml
BSMS 446.xml    BSMS_446.xml
BSMS 447.xml    BSMS_447.xml
BSMS 448.xml    BSMS_448.xml
BSMS 449.xml    BSMS_449.xml
BSMS 450.xml    BSMS_450.xml
BSMS 451.xml    BSMS_451.xml
BSMS 452.xml    BSMS_452.xml
Dd_12_12.xml    Dd_12.12.xml
Dd_12_7.xml     Dd_12.7.xml
Dd_5_39.xml     Dd. 5.39.xml
Dd_5_57.xml     Dd_5.57.xml
Ff_5_9.xml      Ff_5.9.xml
Nn_1_20.xml     Nn_1.20.xml
Oo_6_11.xml     Oo_6.11.xml
Oo_6_14.xml     Oo_6.14.xml
Oo_6_15.xml     Oo_6.15.xml
Oo_6_17.xml     Oo_6.17.xml
Oo_6_29.xml     Oo_6.29.xml
Oo_6_49.xml     Oo_6.49.xml
Or_1124.xml     Or. 1124.xml
Or_1125.xml     Or. 1125.xml
Or_1126.xml     Or. 1126.xml
Or_1127.xml     Or. 1127.xml
Or_1128.xml     Or. 1128.xml
Or_1129.xml     Or. 1129.xml
Or_1130.xml     Or. 1130.xml
Or_1131.xml     Or. 1131.xml
Or_1132.xml     Or. 1132.xml
Or_1133.xml     Or. 1133.xml
Or_1134.xml     Or. 1134.xml
Or_1135.xml     Or. 1135.xml
Or_1136.xml     Or. 1136.xml
Or_1137.xml     Or. 1137.xml
Or_1138.xml     Or. 1138.xml
Or_1139.xml     Or. 1139.xml
Or_1140.xml     Or. 1140.xml
Or_1141.xml     Or. 1141.xml
Or_1142.xml     Or. 1142.xml
Or_1143.xml     Or. 1143.xml
Or_1144.xml     Or. 1144.xml
Or_1145.xml     Or. 1145.xml
Or_1146.xml     Or. 1146.xml
Or_1147.xml     Or. 1147.xml
Or_1148.xml     Or. 1148.xml
Or_1149.xml     Or. 1149.xml
Or_1287.xml     Or. 1287.xml
Or_1292.xml     Or. 1292.xml
Or_1293.xml     Or. 1293.xml
Or_1294.xml     Or. 1294.xml
Or_1295.xml     Or. 1295.xml
Or_1296.xml     Or. 1296.xml
Or_1297.xml     Or. 1297.xml
Or_1298.xml     Or. 1298.xml
Or_1299.xml     Or. 1299.xml
Or_1300.xml     Or. 1300.xml
Or_1301.xml     Or. 1301.xml
Or_1302.xml     Or. 1302.xml
Or_1303.xml     Or. 1303.xml
Or_1304.xml     Or. 1304.xml
Or_1305.xml     Or. 1305.xml
Or_1306.xml     Or. 1306.xml
Or_1307.xml     Or. 1307.xml
Or_1308.xml     Or. 1308.xml
Or_1309.xml     Or. 1309.xml
Or_1310.xml     Or. 1310.xml
Or_1311.xml     Or. 1311.xml
Or_1312.xml     Or. 1312.xml
Or_1313.xml     Or. 1313.xml
Or_1314.xml     Or. 1314.xml
Or_1315.xml     Or. 1315.xml
Or_1316.xml     Or. 1316.xml
Or_1317.xml     Or. 1317.xml
Or_1318.xml     Or. 1318.xml
Or_1319.xml     Or. 1319.xml
Or_1320.xml     Or. 1320.xml
Or_1341.xml     Or. 1341.xml
Or_1342.xml     Or. 1342.xml
Or_1343.xml     Or. 1343.xml
Or_191.xml      Or. 191.xml
Or_1923.xml     Or. 1923.xml
Or_1938.xml     Or. 1938.xml
Or_227.xml      Or. 227.xml
Or_2480.xml     Or. 2480.xml
Or_2544.xml     Or. 2544.xml
Or_2552-3.xml   Or. 2552-3.xml
Or_823.xml      Or. 823.xml
Or_824.xml      Or. 824.xml
Or_825.xml      Or. 825.xml
Or_826.xml      Or. 826.xml
Or_892.xml      Or. 892.xml
Or_929.xml      Or. 929.xml
Or_983.xml      Or. 983.xml
```
The ones with underscores seem to have the higher IDs (e.g. BSMS 443.xml is manuscript_11922 and BSMS_443.xml is manuscript_15229) so I guess they are the scholar's new ones? Deleting the others will mean there won't be any duplicates, but anyone who has bookmarked or cited the old URLs will get an error message when they return. And anyone coming via Google will get the same until it catches up.

**Comment by holfordm** [comment]
Don't forget that he can use the preview-manuscript function for proofreading as well. It's not a great idea to use the website itself to proofread.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yf227** [comment]
You are right! Perhaps I shouldn’t have called it proof reading. He considers the records ready and if there was an issue, I would like to show him the impact it has.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by yf227** [comment]
Many thanks, Andrew!
If for now, I correct the two top level duplicates, I can work my way through the list later.

I am treating this as a priority but will only be able to work on the latter in July.
Would this work?

Best
Yasmin

Yasmin Faghihi
Head of Near and Middle Eastern Department
Manuscripts and Printed Collections
Cambridge University Library
West Road
CB3 9DR UK
Tel.: +44 1223 764739
Email: yf227@cam.ac.uk<mailto:yf227@cam.ac.uk>
Chair Middle East Libraries COMmittee (MELCOM) UK
http://www.melcom.org.uk/
Co-Chair FIHRIST
http://www.fihrist.org.uk/home

**Comment by andrew-morrison** [comment]
To be clear, do you want to fix the two duplicate IDs, then for me to re-index? That would allow your expert to see the new records on the Fihrist web site, but they and everyone else will have 95 duplicate Cambridge classmarks appearing twice in the search results, until you fix them?

Or, do you want me move your last commit to a separate branch? You would then be able to work on them, but they wouldn't be published to the web site, and the expert would have to preview each individually in Oxygen (BTW, [here are some instructions](https://github.com/fihristorg/fihrist-mss/wiki/Configuring-Oxygen-to-Preview-TEI-in-the-Fihrist-Stylesheet) for setting up previewing.)

**Comment by yf227** [comment]
Hi Andrew
Thanks for this.
I would like to fix the latest 4 and leave the fixing of the other records to the cataloguers.
However, what I wonder is, why don’t the records overwrite if they have the same ID?
Ysmn

Yasmin Faghihi
Head of Near and Middle Eastern Department
Manuscripts and Printed Collections
Cambridge University Library
West Road
CB3 9DR UK
Tel.: +44 1223 764739
Email: yf227@cam.ac.uk<mailto:yf227@cam.ac.uk>
Chair
Middle East Libraries COMmittee (MELCOM) UK
http://www.melcom.org.uk/
FIHRIST
http://www.fihrist.org.uk/home
--

**Comment by yf227** [comment]
Hello again…
I have corrected the last duplicates now, by deleting the old files first, then corrected the filename of the new record according to standard.

Some of the duplicates from the list are tricky as they should have just been msItems added to existing files. I will let the cataloguers know.

Others may require deleting by myself. No worries about broken links as we can’t do anything about it.

Have a good weekend!

Yasmin


Yasmin Faghihi
Head of Near and Middle Eastern Department
Manuscripts and Printed Collections
Cambridge University Library
West Road
CB3 9DR UK
Tel.: +44 1223 764739
Email: yf227@cam.ac.uk<mailto:yf227@cam.ac.uk>
Chair
Middle East Libraries COMmittee (MELCOM) UK
http://www.melcom.org.uk/
FIHRIST
http://www.fihrist.org.uk/home
--

**Comment by yf227** [comment]
Hello again…

I have fixed all but these:
Dd_12_12.xml    Dd_12.12.xml
Dd_12_7.xml     Dd_12.7.xml
Dd_5_39.xml     Dd. 5.39.xml
Dd_5_57.xml     Dd_5.57.xml
Ff_5_9.xml      Ff_5.9.xml
Nn_1_20.xml     Nn_1.20.xml

Deleted most of the old records and corrected some.

Would you be able to run the index on Monday, later next week?
I am giving a conference presentation on Tuesday in Naples between 2&3 pm local time.
As long as everything is smooth then (will do a life demo of FIHRIST & GitHub), I’d be very content ☺

Many thanks!
Yasmin

Yasmin Faghihi
Head of Near and Middle Eastern Department
Manuscripts and Printed Collections
Cambridge University Library
West Road
CB3 9DR UK
Tel.: +44 1223 764739
Email: yf227@cam.ac.uk<mailto:yf227@cam.ac.uk>
Chair
Middle East Libraries COMmittee (MELCOM) UK
http://www.melcom.org.uk/
FIHRIST
http://www.fihrist.org.uk/home
--

**Comment by andrew-morrison** [comment]
I will have a go at re-indexing this morning.

**Comment by yf227** [comment]
Thanks, Andrew.

Yasmin Faghihi
Head of Near and Middle Eastern Department
Manuscripts and Printed Collections
Cambridge University Library
West Road
CB3 9DR UK
Tel.: +44 1223 764739
Email: yf227@cam.ac.uk<mailto:yf227@cam.ac.uk>
Chair Middle East Libraries COMmittee (MELCOM) UK
http://www.melcom.org.uk/
Co-Chair FIHRIST
http://www.fihrist.org.uk/home

**Comment by andrew-morrison** [comment]
After fixing a few minor issues, I have been able to re-index. 

But there are still a few that look like pairs of duplicates:

* https://www.fihrist.org.uk/?q=%22Dd._5.39%22
* https://www.fihrist.org.uk/?q=%22Dd._12.12%22
* https://www.fihrist.org.uk/?q=%22Or_1141%22
* https://www.fihrist.org.uk/?q=%22Add_1996%22

Some of the [things I fixed today](https://github.com/fihristorg/fihrist-mss/commit/c67b10e0967d9a2af32e15cc6caa7eb07d713420) I remember fixing before, [back in March](https://github.com/fihristorg/fihrist-mss/commit/e82eca16d6c3689abd48918a5da383cf243cf3be). If, as seems to be the case here, you have experts who go off and work on sets of files, then send them back to you, so you can commit and push them to GitHub, here are a couple of tips:

 * After the web site has been re-indexed, when they subsequently want to resume work on the same record, send them a fresh batch of files taken from your local copy, after having pulled the latest changes back from GitHub.
 * Never rename files unless they are totally wrong (i.e. the filename indicates a different classmark to what's in the TEI). That is because, to answer your question in an earlier comment, the reason duplicates aren't automatically overwritten is GitHub has no concept of IDs. It only manages files. So two files with slightly-different filenames (even only underscores instead of spaces, an extra full stop, or uppercase/lowercase differences) will be stored alongside each other, no matter what IDs are inside the TEI.

What this means is you have broken a lot of what were supposed to be permanent URLs. For example, by deleting BSMS 444.xml (with a space) so that BSMS_444.xml (with an underscore) is the only record for BSMS 444, the top hit for this Google search...

https://www.google.com/search?q=%22BSMS+444%22

...now takes you to an error page. That is because the URL for BSMS 444 used to be...

https://www.fihrist.org.uk/catalog/manuscript_11847

...but is now...

https://www.fihrist.org.uk/catalog/manuscript_15230

It will take a while for Google to re-crawl and re-index our web site, before this is fixed. It is also a problem if anyone has cited a Fihrist URL which has now stopped working.
