### ISSUE TITLE
Query about validation

### ISSUE THREAD

**Issue by ursulaSW** [fihristorg/fihrist-mss#83]
Hi, I hope this is where I'm supposed to raise queries. I don't seem to be able to validate any records. I get this message
![image001](https://user-images.githubusercontent.com/41161861/66592922-ed8f0500-eb8d-11e9-9f66-bca553b712a9.png)
But the same files are OK on Yasmin's computer so it seems my oxygen (15.1) has some problem in connecting to the schema
Ursula

**Comment by andrew-morrison** [comment]
Try the following:

 * Change the href in both xml-model instructions at the top of the TEI document to `https://raw.githubusercontent.com/msdesc/consolidated-tei-schema/master/msdesc.rng`
 * Go to **Options > Preferences** and search for `proxy`. Oxygen 15.1 is quite old, so I'm not sure exactly what options you'll have, but try _Use system systems_, then _Direct connection_ if you have them. If neither work, consult your local IT support about what to fill in for a manual proxy configuration.

You can download the schema files and set up Oxygen to validate using a local copy, but that should be a last resort because it'll mean you won't get updates in the future.
