### ISSUE TITLE
merge issue

### ISSUE THREAD

**Issue by yf227** [fihristorg/fihrist-mss#91]
Not sure what the problem is

**Comment by ElizabethGow** [comment]
It looks like some errors crept into Turkish MS 17 and Persian MS 68 which meant they were no longer valid XML/TEI. I’ve corrected these and pushed them back.

Thanks
Elizabeth
Elizabeth Gow l Part-time Manuscript Curator and Archivist l The John Rylands Research Institute and Library l The University of Manchester Library l The University of Manchester l 150 Deansgate l Manchester l M3 3EH l Tel +44 (0)161 2753541

Working hours: 9.00am-5.00pm, Thursday to Friday

From: Yasmin Faghihi ***@***.***>
Sent: 24 June 2021 17:43
To: fihristorg/fihrist-mss ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fihristorg/fihrist-mss] merge issue (#91)


Not sure what the problem is

**Comment by yf227** [comment]
Thanks Elizabeth.
There were (also?) issues with potential duplications of names.

May I please ask everyone, that when you add a name, that already exists but is clearly not the same person, you add extra information like death dates, or eras of flourishing or anything that you can find in the legacy data, which gives that name further specifications. This would be very helpful.
I resolved those issues by doing exactly that and it worked.

Many thanks
Yasmin


Yasmin Faghihi
Head of Near and Middle Eastern Department
Manuscripts and Printed Collections
Cambridge University Library
West Road
CB3 9DR UK
Tel.: +44 1223 764739
Email: ***@***.******@***.***>
Chair
FIHRIST
http://www.fihrist.org.uk/home


From: ElizabethGow ***@***.***>
Reply-To: fihristorg/fihrist-mss ***@***.***>
Date: Friday, 25 June 2021 at 09:24
To: fihristorg/fihrist-mss ***@***.***>
Cc: Yasmin Faghihi ***@***.***>, Author ***@***.***>
Subject: Re: [fihristorg/fihrist-mss] merge issue (#91)

It looks like some errors crept into Turkish MS 17 and Persian MS 68 which meant they were no longer valid XML/TEI. I’ve corrected these and pushed them back.

Thanks
Elizabeth
Elizabeth Gow l Part-time Manuscript Curator and Archivist l The John Rylands Research Institute and Library l The University of Manchester Library l The University of Manchester l 150 Deansgate l Manchester l M3 3EH l Tel +44 (0)161 2753541

Working hours: 9.00am-5.00pm, Thursday to Friday

From: Yasmin Faghihi ***@***.***>
Sent: 24 June 2021 17:43
To: fihristorg/fihrist-mss ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fihristorg/fihrist-mss] merge issue (#91)


Not sure what the problem is
