### ISSUE TITLE
seperating titles

### ISSUE THREAD

**Issue by yf227** [fihristorg/fihrist-mss#96]
Hi Andrew, I have moved this entry from works_additions to works_base <bibl xml:id="work_21378">
                    <title type="uniform">Ghazalīyāt | Amīr Yādgār Bayg Sayfī</title>
                    <title type="variant">غزليات</title>
                    <title type="variant">Ghazals</title>
                    <title type="variant">Persian ghazals</title>
                    <title type="variant">Ghazalīyāt-i Amīr Yādgār Bayg Sayfī</title>
                    
                    
                    
                </bibl>
than deleted the link to MS_Elliot_134 as these are different works. 
Am I correct in assuming that these will reappear in wors_additions after indexing?

**Comment by andrew-morrison** [comment]
Running the works authority updating script does generate a new work ID for "Ghazals" (غزليات) in works_additions.xml. If does so because there are two msItem in MS_Elliott_134.xml with that title and blank key attributes. It has also found 18 pre-existing work IDs in works_base.xml with the same title too (I'm guessing ghazals are a type or genre of writing, not the title of a specific work.)

Do you want me to commit that change to works_additions.xml? If you have uncommitted or unpushed changes of your own to the same file it might conflict?

**Comment by yf227** [comment]
I have pushed all my changes from last night. 
As for the Ghazals (a type of poetry) in MS_Elliot_134, these are two separate works by different authors, so will need individual work_ids.
One of them (item3) relates to a very annoying record containing a portion of that work, i.e. work_21064. 
The other one (item5) will need creating a work entry.
In fact both need a new work entry but I can use work_21064 for item3 and do something about the BL record.

**Comment by andrew-morrison** [comment]
OK. done. Pull to update your local copy.

Note that the updater script ensures IDs are unique by finding the highest number already in the authority files, then starts creating new IDs by adding one for each new entry required. If you need more entries, you can so the same. The new one just created is work_21411, so you can manually create work_21412, and work_21413, if you need them. As long as you commit and push them immediately after creating them, so that when I next run the updater script it'll find your new ones, and start creating from the new highest number, plus one.

Please close this issue if you're happy to proceed.

**Comment by yf227** [comment]
Ok, thanks. Done it, with nerves...LOL...I hoe its alright! closing now.
